### ISSUE TITLE
Welcome User Message 

### ISSUE THREAD

**Issue by j-mrles** [j-mrles/DjangoRestaurant#24]
After logging in display "welcome user" in the reservation page.

**Comment by gabe-vega** [comment]
Currently, after logging in, the system displays "Welcome, [firstname]" (with the bracketed firstname replaced by the user's actual firstname lol) based on a query in views that retrieves the firstname from the User table using the users firstname. Potentially, we may need to refactor this because multiple users can have the same firstname, so may need to consider adding a unique user_id field, to specifically refer to each user
- welcome message displays
- added css to match formatting
- consider refactoring user table code to include an id

**Comment by gabe-vega** [comment]
![welcome-user-ss](https://github.com/user-attachments/assets/afb0906b-39ee-4bd0-9a1c-41fdb92a1fd6)
